### ISSUE TITLE
The letters disappear while screen scrolling..

### ISSUE THREAD

**Issue by kent58909** [zellij-org/zellij#397] opened 2021-04-28 01:26 UTC
![image](https://user-images.githubusercontent.com/59190957/116331958-6d79d000-a803-11eb-91e0-bbd4fdefedb2.png)

if screen scrolled, some letters will disappear, please see the picture...

## Information

`zellij --version`:

**Comment by imsnif** [comment] 2021-05-05 17:09
Hey @bernadit - if this still happens for you in version 0.7.0, could you please:

1. Delete the contents of `/tmp/zellij/zellij-log`.
2. Run `zellij --debug` and then recreate your issue.
3. Quit Zellij immediately with ctrl-q (your bug should ideally still be visible on screen)

Please attach the files that were created in

`/tmp/zellij/zellij-log/`

To the extent you are comfortable with.

Also please add the size in columns/lines of the terminal in which the bug happened. You can usually find these out with `tput lines` and `tput cols`.

**Comment by bernadit** [comment] 2021-05-13 04:27
![image](https://user-images.githubusercontent.com/59190957/118077295-6c8d9480-b3e6-11eb-9ae2-238cfdffac01.png)

yes, the version is 0.9.0 now... please see the pic...

by the way.... i use the terminal guake.

**Comment by imsnif** [comment] 2021-05-13 07:29
Thanks @bernadit - I can't really debug this though like this... If you could follow the instructions here and attach the log files, that would be a huge help: https://github.com/zellij-org/zellij/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by woelfman** [comment] 2021-09-01 17:37
This is still an issue with master (6ec5195). It's easy to reproduce with:
```sh
for i in `seq 100`; do echo $i; sleep 0.1; done
```
If you scroll while text is being output you will corrupt the display buffer. Hitting enter when the loop is done will cause the the missing lines to be output in a messy order.

Ideally the buffer would stop scrolling if the last line is not visible so you can inspect the output. Today it will continue to scroll, but with an offset of however many lines you scrolled up.

**Comment by imsnif** [comment] 2021-09-01 18:01
This issue sounds like: https://github.com/zellij-org/zellij/issues/306
But I'm not sure if this is what OP was referring to?

If so, @kunalmohan is working on a fix for this.

**Comment by woelfman** [comment] 2021-09-01 18:22
@imsnif I think you're right. What I'm observing seems to be more closely described in #306. Thank you.

**Comment by raphCode** [comment] 2022-04-28 09:26
this seems to be solved and can be closed?

**Closed** 2022-04-28 09:59 UTC
Labels: bug, compatibility
