### ISSUE TITLE
Apple M1 breaks IPC connection when kernel buffers are full

### ISSUE THREAD

**Issue by jaysonsantos** [zellij-org/zellij#1718] opened 2022-09-08 16:45 UTC
This will probably sound really silly but it seems that when I have an internet outage for a few minutes, macOS cannot send ipc messages (does zellij use unix sockets?) because the kernel buffer is full, panicking (here)[https://github.com/zellij-org/zellij/blob/588167f38e9581a9d6228577829fe4d6b15c34dc/zellij-utils/src/ipc.rs#L161].

I kinda screwed up and opened another zellij session so I lost the contents of /tmp/zellij-uid but i've managed to get a simple stack trace:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidValueWrite(InvalidMarkerWrite(Os { code: 55, kind: Uncategorized, message: "No buffer space available" }))', /private/tmp/zellij-20220818-50395-1ya2le5/zellij-0.31.3/zellij-utils/src/ipc.rs:161:69
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[?1049h[?1l=[r[?1000l[?1002l[?1003l[?1005l[?1006l[?12l
```

`zellij --version`: zellij 0.31.3
`stty size`: 61 263
`uname -av` or `ver`(Windows): Darwin Jaysons-MBP.localdomain 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000 arm64

List of programs you interact with as, `PROGRAM --version`:
`alacritty --version`: alacritty 0.10.1 (2844606)

**Further information**
So far, the only thing I could notice is that the internet seems to be down, and the whole system gets kinda slugish meaning it is not a problem with zellij but, does it make sense to make a retry mechanism for that call instead of panicking?

**Comment by imsnif** [comment] 2022-09-09 11:48
I'm honestly shocked to find out network connectivity affects UNIX sockets on the M1... but I suppose other people have different ideas about this :)

In any case, a fix for this (and other similar issues caused by the same code-path) has just been released in version `0.31.4`. What now happens is that the client part of Zellij will disconnect and the server part will stay up, so you can `zellij attach` or `zellij attach <session_name>` if you have more than one session afterwards and come back to your session.

**Closed by imsnif** 2022-09-09 11:48 UTC
Labels: bug
