### ISSUE TITLE
Weird mousescroll issue with Kitty

### ISSUE THREAD

**Issue by danillos** [zellij-org/zellij#1716] opened 2022-09-07 21:58 UTC
**Basic information**

`zellij --version`: zellij 0.31.3
`stty size`:38 176
`uname -av`: Darwin 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000 arm64
`kitty --version`: kitty 0.26.2 created by Kovid Goyal

**Further information**

When doesn't have anything to scroll and I scroll it, it starts to add some texts:

```
66;18;29M66;18;29M66;18;29M67;18;29M67;18;29M66;18;29M66;18;29M66;18;29M67;18;29M67;18;29M66;18;29M66;18;29M66;18;29M67;18;29M67;18;29M67;18;29M66;18;29M67;18;29M66;18;29M
67;18;29M66;18;29M66;18;29M66;18;29M67;18;29M67;18;29M67;18;29M66;18;29M
```

I guess it happens scrolling to sides like left / right. Using Alacritty and Iterm2 it works.

**Comment by tlinford** [comment] 2022-09-09 07:37
Just to be clear, it works properly with alacritty or iterm2 + zellij?

**Comment by danillos** [comment] 2022-09-09 19:02
Hi @tlinford,

Yes, it works:

```
zellij + alacritty = no issues
zellij + Iterm2 = no issues
zellij + Terminal = no issues
zellij + Kitty = fails
Just Kitty = no issues
```


And I confirmed it, it only happens doing side scrolling like on `Mac Touchpad` and `shift + mousewheel`.

**Comment by nozwock** [comment] 2022-10-14 21:27
Similar issue of these weird escape sequences on kitty when side scrolling.
Zellij works fine with other terminals (or just kitty) as @danillos mentioned above.
![unknown](https://user-images.githubusercontent.com/57829219/195945402-98b43ab2-7aa7-467f-b9cc-3213b7152c0b.png)

**Comment by Noxime** [comment] 2022-11-10 07:59
Same or similar issue occurs on Windows Terminal (the new one, not cmd). Zellij 0.32.0 is running through an SSH session in an Ubuntu 20 environment. I have not been able to consistently reproduce the issue through specific scrolling motion, however it happens often (every ~10 seconds) when scrolling through the history. This is on a regular Logitech mouse and no sideways scrolling.

**Comment by tlinford** [comment] 2022-11-10 15:06
Had another look at this, looks like `termwiz` does not support these horizontal scroll events yet.
I'll open an issue there, hopefully it won't be too hard to get this working!

**Comment by tlinford** [comment] 2023-01-18 08:41
Just a note, I initially thought I could not reproduce this, but apparently `fish` simply disregards these sequences and they were not showing up.

**Comment by Nouzan** [comment] 2023-02-05 04:09
This issue also occurs when using with the dev version of Alacritty since https://github.com/alacritty/alacritty/pull/6625 being merged.

**Comment by tlinford** [comment] 2023-02-07 08:08
> This issue also occurs when using with the dev version of Alacritty since [alacritty/alacritty#6625](https://github.com/alacritty/alacritty/pull/6625) being merged.

Thanks for the info!
The fix we needed to solve this got merged in termwiz so we should be able to get this solved for the next release.

**Closed** 2023-02-17 10:01 UTC
Labels: bug

**Comment by nozwock** [comment] 2023-03-12 10:09
Amazing! the biggest annoyance is gone now :⁠-⁠P
