### ISSUE TITLE
Ion shell compatibility problem

### ISSUE THREAD

**Issue by Delamare2112** [zellij-org/zellij#597] opened 2021-07-03 17:55 UTC
**Basic information**

`zellij --version`: 0.13.0
`tput lines`: 42
`tput cols`: 134
`uname -av`: Linux manjaro 5.12.9-1-MANJARO #1 SMP PREEMPT Thu Jun 3 14:56:42 UTC 2021 x86_64 GNU/Linux

`alacritty --version`: alacritty 0.9.0-dev (fa2fa398)
Ion Shell version: git (https://gitlab.redox-os.org/redox-os/ion) (a7c02229)

**Further information**

Zellij becomes frozen when doing anything that spawns a new ion shell beyond the first initial shell.  Like when creating a new pane or tab for example.  

I tried using different terminals and window managers until I found that the problem is Zellij + Ion Shell.  If I switch my default shell to Zsh and relog, the problem goes away.

Repro:  
1. use `chsh` to make ion your default shell
1. logout of your system, then log back into your system
1. `zellij`
1. `echo "inside"` (works fine)
1. `Ctrl+p` `n`
1. Zellij is frozen now but type (without feedback) `echo "outside"`
1. (in another terminal) `killall -2 zellij` (or some other method of closing your frozen Zellij)
1. Notice that `echo "outside"` and `outside` were both printed after Zellij closes.

**Comment by Delamare2112** [comment] 2021-07-03 17:57
Oh yeah!  The log files!  Here they are:  

[zellij-7.log](https://github.com/zellij-org/zellij/files/6758828/zellij-7.log)
[zellij-8.log](https://github.com/zellij-org/zellij/files/6758829/zellij-8.log)
[zellij-9.log](https://github.com/zellij-org/zellij/files/6758830/zellij-9.log)

**Comment by a-kenji** [comment] 2021-07-03 19:35
Hey @Delamare2112.
Thank you for reaching out and filing this bug!
I can reproduce it quite easily.
I wonder what could cause this.
I'll try to look into it some more.

**Comment by a-kenji** [comment] 2021-07-04 11:10
This problem is also apparent with nu shell.
To reproduce:
```
zellij options --default-shell ion
zellij options --default-shell nu
```
And try to start a new tab/pane.

**Comment by imsnif** [comment] 2021-07-05 16:36
Hey @Delamare2112, thanks for reporting and debugging this. And also thanks @a-kenji as well.

This was happening because the `pty` thread inside Zellij did not manage to properly close these shells (ion or nu). It was sending them the SIGKILL which I guess under certain circumstances was not enough for them to die (I'm not sure which circumstances exactly - I for example only managed to reproduce this with the development build of ion and not with any build of nu).

I issued a fix for this which should be merged to `main` just as soon as the CI gives me a go. If you'd like to test it there to make sure, that would be great - otherwise it'll be released with the next version in the not-too-distant future.

**Comment by a-kenji** [comment] 2021-07-05 17:30
@imsnif 
Awesome, thanks for the quick fix.
It behaves well on my side now.
Yes the problem with nu was not with
every single launch.

**Comment by Delamare2112** [comment] 2021-07-05 18:33
It works!  Thanks very much for the bug fix :)

**Closed** 2021-07-05 18:34 UTC
Labels: bug
