### ISSUE TITLE
Windows - NTAPI lib build errors

### ISSUE THREAD

**Issue by JABirchall** [zellij-org/zellij#2641] opened 2023-07-21 23:08 UTC
Zellij is unable to build on windows using `cargo install zellij`

The build error log:

```
error[E0793]: reference to packed field is unaligned
    --> C:\Users\owner\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ntapi-0.3.7\src\ntexapi.rs:2783:52
     |
2783 |         *tick_count.QuadPart_mut() = read_volatile(&(*USER_SHARED_DATA).u.TickCountQuad);
     |                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
     = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

error[E0793]: reference to packed field is unaligned
    --> C:\Users\owner\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ntapi-0.3.7\src\ntexapi.rs:2807:25
     |
2807 |         ((read_volatile(&(*USER_SHARED_DATA).u.TickCountQuad)
     |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
     = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

   Compiling vtparse v0.6.2
   Compiling dirs v4.0.0
For more information about this error, try `rustc --explain E0793`.
error: could not compile `ntapi` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `zellij v0.37.2`, intermediate artifacts can be found at `C:\Users\owner\AppData\Local\Temp\cargo-installSXAdrX`
```

**Basic information**
`zellij --version`: zellij v0.37.2
`uname -av` or `ver`(Windows): Microsoft Windows [Version 10.0.19045.3208]

**Comment by Zykino** [comment] 2023-07-22 08:47
As the maintainer often say:

> Still a duplicate of https://github.com/zellij-org/zellij/issues/316
> Please especially see this comment: https://github.com/zellij-org/zellij/issues/316#issuecomment-1406551269

If you can, you can still install and use Zellij inside WSL (maybe just WSL2, I tried only this version).

**Comment by imsnif** [comment] 2023-07-22 11:47
Thanks @Zykino - closing this as a duplicate of #316

**Closed by imsnif** 2023-07-22 11:47 UTC
Labels: bug
