### ISSUE TITLE
The first start cannot match the size of the terminal

### ISSUE THREAD

**Issue by lisiur** [zellij-org/zellij#1238] opened 2022-03-18 01:46 UTC
**Basic information**
```
INFO   |zellij_client            | 2022-03-18 09:36:32.583 [main      ] [/home/lisiur/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-client-0.26.0/src/lib.rs:121]: Starting Zellij client! 
INFO   |zellij_server            | 2022-03-18 09:36:32.585 [main      ] [/home/lisiur/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.26.0/src/lib.rs:188]: Starting Zellij server! 
INFO   |zellij_server::wasm_vm   | 2022-03-18 09:36:32.637 [wasm      ] [/home/lisiur/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.26.0/src/wasm_vm.rs:87]: Wasm main thread starts 
INFO   |zellij_server::wasm_vm   | 2022-03-18 09:36:33.759 [wasm      ] [/home/lisiur/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.26.0/src/wasm_vm.rs:226]: wasm main thread exits 
INFO   |zellij_client            | 2022-03-18 09:36:33.759 [main      ] [/home/lisiur/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-client-0.26.0/src/lib.rs:347]: Bye from Zellij! 
```

`zellij --version`: zellij 0.26.0
`tput lines`: 21
`tput cols`: 80
`uname -av` or `ver`(Windows): Linux day 5.13.0-36-generic #41~20.04.1-Ubuntu SMP Tue Mar 8 09:16:51 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

List of programs you interact with as, `PROGRAM --version`: 
`terminator --version`: terminator 1.91 

**Further information**
Configure the translator to automatically fullscreen when activated, and the start script is configured to `zellij`:
![screenshot](https://user-images.githubusercontent.com/15188817/158921621-5fc8d022-369d-4659-b4b9-8ddac0a20343.png)

**Comment by a-kenji** [comment] 2022-03-18 07:56
Thanks for reaching out!
This is a duplicate of #741 .

**Closed** 2022-03-18 08:00 UTC
Labels: bug, duplicate
