### ISSUE TITLE
interrupting cat (CTRL-C) panics `stdin_handler_thread`

### ISSUE THREAD

**Issue by ahirner** [zellij-org/zellij#1340] opened 2022-04-24 16:45 UTC
**Basic information**

`zellij --version`: 0.28.1
`tput lines`: 56
`tput cols`: 205
`uname -av` or `ver`(Windows): `Darwin speyside.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64`

- `alacritty --version`: alacritty 0.10.0 (8a26dee)
- https://github.com/casonadams/z-tab-bar 0.2.0

**Further information**

1. `cat <really long text file>`
2. `CTRL-C` (repeat 1. if it doesn't hang immediately)
3. Observe that any input and output is stuck
4. `killall zellij` in another session
5. Observe backtrace in originating session:

```
  × Thread 'router' panicked.
  ├─▶ Originating Thread(s)
  │   	1. stdin_handler_thread: AcceptInput
  │   	2. screen_thread: ClearScroll
  │   	3. ipc_server: Render
  │
  ├─▶ At /Users/dafcok/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-utils-0.28.1/src/ipc.rs:188:55
  ╰─▶ called `Result::unwrap()` on an `Err` value: Io(Error { kind: UnexpectedEof, message: "failed to fill whole buffer" })
  help: If you are seeing this message, it means that something went wrong.
        Please report this error to the github issue.
        (https://github.com/zellij-org/zellij/issues)

        Also, if you want to see the backtrace, you can set the `RUST_BACKTRACE` environment variable to `1`.
```

Subjectively, it panics more frequently if a second pane is open.
[1.txt](https://github.com/zellij-org/zellij/files/8550104/1.txt)

**Comment by raphCode** [comment] 2022-04-25 20:32
Hi, thanks for reporting this!

Sadly, I was not able to reproduce this in a few tries on Arch.

Since this sounds like a racing bug which is influenced by timing, I am interested in your hardware setup: What computer do you experience this bug on?

> Subjectively, it panics more frequently if a second pane is open.

Is the second pane empty in this case or is something running in there?
Was the system idle or maxed out?
Does the system load influence the likelihood of the bug?

Are you running the official release or a a custom (debug?) build?

**Comment by imsnif** [comment] 2022-04-26 07:28
If I may interject here - the trace seems to lead to the ipc receive method: https://github.com/zellij-org/zellij/blob/main/zellij-utils/src/ipc.rs#L188

As far as I'm aware, the only place we use this is when receiving events on the Zellij server from the Zellij clients. 99% of the time, those events are keypresses (like in the example here). I guess what's happening is that for some reason (resource constraints? Maybe Zellij is running on a 1 CPU machine? just guessing) the server is too busy to handle the message and it gets corrupted on the channel (haven't looked deeply at what the buffering situation is there).

Evidently, as opposed to our initial assumption, this process can fail. Due to the nature of this channel, I think it's totally fine to just silently fail here. That's actually what I'd be expecting as a user (I don't want my ctrl-c to be buffered and happen later after I pressed it 10 times - that would be annoying :) ).

So essentially, I think a fix for this can be to:
1. `match` against this line
2.  in case of an error, do nothing (maybe do a `log::error` of it if we're feeling fancy)
3. otherwise, proceed as normal

I think this method needs to return an Event though, so might need to create a `Noop` variant or something along those lines.

What do you think @raphCode ?

**Comment by a-kenji** [comment] 2022-04-26 08:00
I think we should log, if an error happens there.

**Comment by raphCode** [comment] 2022-04-26 14:44
OP reported the panic only happens when killing the client, the real issue being a hang beforehand?

---

The above comment originated while analyzing the panic more closely, this was the text I wanted to write originally:

A quick fix would be indeed to log and ignore the error, but I really would like to understand the cause of the error more deeply. This is motivated by my curiosity, and because it feels wrong to just add some `Noop` to return.

I tried to find out which part of the "pipeline" did throw the error:
The IO error may arise at `BufReader`'s `read()` or the `LocalSocketStream`'s `read()`.
Depending on which call fails, this raises different questions for me:
- `BufReader::read()`: Why does the BufReader not expect any EOF? It is a wrapper around any `Read` instance, which could contain EOF at any time.
- `LocalSocketStream::read()`: I only expect to see EOF here when the socket is closed, which should not happen unless the client is killed.

**Comment by imsnif** [comment] 2022-04-26 14:55
I would guess the hang happens because of the read method in the channel. I'm honestly not sure what's going on there - but if you feel like debugging this further, you are of course most welcome. :)

I personally don't know this part of the code super well and have to rely on reverse engineering it to fully understand what's up - but I have a feeling you'll manage to figure it out if you want. Let me know if I can offer a hand.

I have seen this error crop up in various other instances, so I think recovering from a bad channel state would be good for us here, and the UX of one command being lost in these very edge of edge cases (instead of the whole app crashing) is not too bad.

**Comment by imsnif** [comment] 2022-04-26 18:14
> Sadly, I am not sure if I can investigate further without being able to reproduce.

Yeah, that makes sense. So shall we go for the Noop solution? Would you like to implement it or shall I?

> Also, I am not experienced in debugging Rust - I see there is a rust-specific fork of gdb. Ideally, I also find a good terminal based UI for gdb, using it vanilla is a bit ... unpleasant.

Unfortunately I can't help you there. I'm a printf debugger myself :)

**Comment by raphCode** [comment] 2022-04-26 19:20
Ideally, @ahirner can tell us something to get to the root of the issue.

> So shall we go for the Noop solution?

You can try, but I am afraid to solve the "hang" issue we need to make `read()` nonblocking, which would return immediately on an empty channel. Repeatedly retrying the `read()` sounds a lot like CPU intense polling to me?

**Comment by ahirner** [comment] 2022-04-27 07:34
> Ideally, @ahirner can tell us something to get to the root of the issue.

Sorry, a bit short on time.

> What computer do you experience this bug on?
Maybe Zellij is running on a 1 CPU machine? 

Macbook 2 GHz Quad-Core Intel Core i5.

> Was the system idle or maxed out?

There were no other heavy processes running.

> Does the system load influence the likelihood of the bug?

I'm not sure. I got the same error in various cases where stdout is flooded and then interrupted. Also from a remote ssh session.

> Are you running the official release or a a custom (debug?) build?

cargo installed 0.28.1

**Comment by imsnif** [comment] 2022-04-27 08:27
Hey @ahirner - I issued a fix for this here: https://github.com/zellij-org/zellij/pull/1351

The fix recovers from this state and logs a message. My assumption is that as a user you will hardly notice anything (worst case have to ctrl-c one extra time), but I might be wrong.

I'm going to close this issue, but once we release a version (or once I merge the PR if you feel like running from source to test), could you give it a shot, reproduce the issue and let us know if it works well for you?

**Closed** 2022-04-27 17:33 UTC
Labels: bug, darwin, stability
