### ISSUE TITLE
Neovim cursor doesn't change

### ISSUE THREAD

**Issue by rYR79435** [zellij-org/zellij#552] opened 2021-05-30 11:14 UTC
**In Case of Graphical or Performance Issues**

1. Delete the contents of `/tmp/zellij-1000/zellij-log`, ie with `cd /tmp/zellij-1000/` and `rm -fr zellij-log/`
2. Run `zellij --debug`
3. Recreate your issue.
3. Quit Zellij immediately with ctrl-q (your bug should ideally still be visible on screen)

Please attach the files that were created in `/tmp/zellij-1000/zellij-log/` to the extent you are comfortable with.
[zellij-8.log](https://github.com/zellij-org/zellij/files/6566087/zellij-8.log)
[zellij-9.log](https://github.com/zellij-org/zellij/files/6566088/zellij-9.log)
[zellij-10.log](https://github.com/zellij-org/zellij/files/6566089/zellij-10.log)

**Basic information**

`zellij --version`: zellij 0.13.0
`uname -av` or `ver`(Windows): 5.12.8-arch1-1

`alacritty --version`: alacritty 0.8.0 (a1b13e68)
`nvim --version`: NVIM v0.4.4 (from Arch repo)

**Further information**
Reproduction steps, noticable behavior, related issues etc
This is essentially the same issue as #484, except the inverse is happening (and it's nvim, not vim).
**I expect:** normal: block, insert: beam.
**I get:** normal: beam,  insert: beam.

It happens irrespective of terminal size, hence I omitted the tput info.

**Comment by a-kenji** [comment] 2021-05-30 13:33
Thank you for taking the time in creating this issue!

**Comment by imsnif** [comment] 2021-08-20 13:09
Hey @rYR79435 - does this still happen to you in the latest version?
If so, would you mind giving some more details?

For me, when I open nvim, the cursor is a block and when I go to insert mode it turns into a beam. When I `cat` the log file you attached, I see that I'm in "INSERT" mode and that the cursor is a beam. Could it be that the issue has been solved, or am I misunderstanding something?

**Comment by rYR79435** [comment] 2021-08-24 06:57
Thank you for following up on this.
I have tried again with version `0.15.0` and it still happens.

My neovim config is as follows:
```
set guicursor=a:ver1, " bar by default
set guicursor+=r-v:hor1, " underline in replace and visual
set guicursor+=n-sm:block " block in normal and showmatch
```
This config fully works without zellij.
With zellij, the cursor changes to underline when I go into replace/visual mode and it changes back to bar for any other mode. I never changes to block, which it should in normal/showmatch.

For completeness' sake, the basic info again:
`zellij --version`: zellij 0.15.0
`uname -av`: 5.13.12-arch1-1

`alacritty --version`: alacritty 0.9.0 (fed349aa)
`nvim --version`: NVIM v0.5.0 (from Arch repo)

**Comment by imsnif** [comment] 2021-08-24 13:41
Hey, @rYR79435 - thanks for the explanation. Now I managed to understand the issue and find the cause. I issued a fix for this and it should be released in the next version.

**Closed** 2021-08-25 11:43 UTC
Labels: bug, compatibility
