### ISSUE TITLE
[feature request] make `attach --create my-session` simply attach to `my-session` if it already exists

### ISSUE THREAD

**Issue by meleu** [zellij-org/zellij#2279] opened 2023-03-12 00:14 UTC
First of all: thanks for creating Zellij! It's my second day using it (after years of using tmux) and I'm excited! :)

Now, my feature request:

Make `zellij attach --create my-session` simply attach to `my-session` if it already exists, or create it if it doesn't.

Currently when I use `attach --create` with an existing session, I receive this error:

`Session with name "my-session" already exists. Use attach command to connect to it or specify a different name.`

Such behavior makes it look like a long alias to `zellij --session my-session`.

**Comment by yves-biener** [comment] 2023-03-12 10:51
The described feature request is already intended behavior. Due to a bug, fixed with #2247, the `attach --create` command errored with an existing session instead of attaching to that session.

**Comment by jaeheonji** [comment] 2023-03-12 11:06
@yves-biener Thanks for letting us know the history.
@meleu If you want to discuss or have a new suggestion, please create a new issue!

Thank you everyone.

**Closed by jaeheonji** 2023-03-12 11:06 UTC
Labels: enhancement, discussion
