### ISSUE TITLE
Zellig crashes when pasting long line continued shell commands

### ISSUE THREAD

**Issue by talios** [zellij-org/zellij#528] opened 2021-05-20 23:08 UTC
I had zellig running with 3 panes - two were running my server/webserver instances, the third I was running `curl` statements to the server.

After copying a rather long, line continuated curl ala:

```
curl -k -v -u $USERNAME $URL \
  -H 'Connection: keep-alive' \
  -H 'sec-ch-ua: "Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"' \
  -H 'DNT: 1' \
  -H 'Accept-language: en' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' \
  -H 'Accept: application/hal+json' \
  -H 'X-Requested-With: Ext.basex' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4503.0 Safari/537.36' \
  -H 'Origin: https://localhost:3000' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Referer: https://localhost:3000/' \
  -H 'Cookie: ai_user=VR/t7|2021-01-20T21:50:14.080Z' \
  --data-raw '*******' \
  --compressed \
  --insecure
```

zellij immediately crashed with the following backtrace:

```
~ took 37m40s ✖  zellij
Originating Thread(s):
1. stdin_handler_thread: AcceptInput
2. screen_thread: WriteCharacter

Error: thread 'screen' panicked at 'failed to write to terminal: Sys(EAGAIN)': zellij-server/src/tab.rs:633
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: zellij_utils::errors::handle_panic
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic_handler::{{closure}}
   5: std::sys_common::backtrace::__rust_end_short_backtrace
   6: _rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
   9: zellij_server::tab::Tab::write_to_pane_id
  10: zellij_server::screen::screen_thread_main
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: __pthread_start
~ took 36s ✖
```

**Basic information**

`zellij --version`: zellij 0.12.0 ( build from HEAD this morning )
`uname -av` or `ver`(Windows): Darwin Grey-Beard.fritz.box 20.4.0 Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:47 PDT 2021; root:xnu-7195.101.2~1/RELEASE_X86_64 x86_64

This doesn't appear to _always_ happen, and I can't definitively reproduce it at will :(

**Comment by kxt** [comment] 2021-05-21 03:30
The problem is that ptys are opened with `O_NONBLOCK` set:
https://github.com/zellij-org/zellij/blob/main/zellij-server/src/os_input_output.rs#L91

This flag allows Darwin to say `EAGAIN` on writes whenever it feels like. This should not be a problem, but right now there is no handling of `EAGAIN` in `write_to_pane_id`, it just panics with the "failed to write to terminal" message.

`O_NONBLOCK` is set because reading from pty relies on it. However, #523 changes this and removes `O_NONBLOCK` from the pty, so it should fix this issue too.

**Comment by kxt** [comment] 2021-05-24 15:19
With #523 being merged, this bug should be resolved. @talios can you give main HEAD a try?

**Comment by a-kenji** [comment] 2021-11-15 07:59
@talios 
Is that still an issue you experience with recent versions?

**Comment by imsnif** [comment] 2022-03-25 08:27
Closing, as this has been fixed a while ago

**Closed by imsnif** 2022-03-25 08:27 UTC
Labels: bug, darwin, stability
