### ISSUE TITLE
Will zellij come to windows?

### ISSUE THREAD

**Issue by leet0rz** [zellij-org/zellij#2843] opened 2023-10-09 11:32 UTC
PLEASE!

**Comment by imsnif** [comment] 2023-10-09 11:37
Duplicate of https://github.com/zellij-org/zellij/issues/316... I also see you already commented there, so not entirely sure why you opened a new issue.

**Closed by imsnif** 2023-10-09 11:37 UTC

**Comment by leet0rz** [comment] 2023-10-14 09:48
> Duplicate of #316... I also see you already commented there, so not entirely sure why you opened a new issue.

In hopes that you'll pull through with support for windows, many of us need it.
