### ISSUE TITLE
2023 still can not build on windows

### ISSUE THREAD

**Issue by lucasjinreal** [zellij-org/zellij#2629] opened 2023-07-17 02:15 UTC
```
200 |         let sock_fd = self.sender.get_ref().as_raw_fd();
    |                                             ^^^^^^^^^ method not found in `&interprocess::local_socket::LocalSocke
tStream`

error[E0599]: no function or associated item named `from_raw_fd` found for struct `interprocess::local_socket::LocalSock
etStream` in the current scope
```

Does this really not trying to support windows at all?

**Comment by imsnif** [comment] 2023-07-17 08:02
Still a duplicate of https://github.com/zellij-org/zellij/issues/316

Please especially see this comment: https://github.com/zellij-org/zellij/issues/316#issuecomment-1406551269

**Closed by imsnif** 2023-07-17 08:02 UTC
Labels: bug

**Comment by lucasjinreal** [comment] 2023-07-17 08:22
@imsnif thank u sir, do u have any alternative suggestions which do same as zellij and able to run on windows?

**Comment by imsnif** [comment] 2023-07-17 08:25
Look into WSL - many people use it for running Zellij on windows. I will not be replying to this issue further.
