### ISSUE TITLE
Compatibility: Neovim

### ISSUE THREAD

**Issue by luqmanishere** [zellij-org/zellij#299] opened 2021-04-21 06:15 UTC
My neovim doesn't display color properly on zellij.
Here is neovim on tmux:
![2021-04-21_134904_xps-arch](https://user-images.githubusercontent.com/82690512/115503016-5fc6c680-a2a8-11eb-87a5-5764b3d62308.png)

Here it is on zellij:
![2021-04-21_135033_xps-arch](https://user-images.githubusercontent.com/82690512/115503163-900e6500-a2a8-11eb-8da9-cea86c57db10.png)

The colors are.... not colors. Other colors show fine.
![2021-04-21_140543_xps-arch](https://user-images.githubusercontent.com/82690512/115504525-afa68d00-a2aa-11eb-9f83-0bde36cc6039.png)

The cursor is also messed up. It's supposed to change to to a line in insert mode:
![2021-04-21_135157_xps-arch](https://user-images.githubusercontent.com/82690512/115503312-cba92f00-a2a8-11eb-8dfe-b18bca36d31e.png)

In zellij:
![2021-04-21_135436_xps-arch](https://user-images.githubusercontent.com/82690512/115503544-29d61200-a2a9-11eb-8c64-82473951614a.png)

The cursor also doesn't change in some other TUI's like nmtui.

The terminal im using is kitty. Switching to konsole restores the colors on neovim but doesn't solve the cursor issue.

Kitty provides its own termcap, but i'm not sure if that causes any issues.

OS : Arch Linux

**Comment by alexhallam** [comment] 2021-04-21 16:08
I use neovim also. I am using the windows terminal. I am not having these issues. Maybe this is more about kitty? Just thought I would add my perspective to help narrow this bug down.

**Comment by alexhallam** [comment] 2021-04-21 16:10
I take that back. I am not having color problems, but the cursor is not rendering right.

**Comment by luqmanishere** [comment] 2021-04-22 00:33
Yeah, the color thing seems to be a kitty issue. Tested with konsole and gnome-terminal, both shows colors fine. But the cursor issue persists across all these terminals.

**Comment by lunush** [comment] 2021-04-22 11:44
I am also having the cursor issue. In both vi mode in zsh and neovim, the cursor always stays as a beam.

**Comment by a-kenji** [comment] 2021-04-22 12:26
Thank you! I think I can reproduce that behaviour. Some codes are not handled.

If you want to further help triage:
`zellij --debug` & in `/tmp/zellij/zellij-log/log.txt` there should be erros.
Would be awesome if you could upload your log files.

Here is mine:
[log.txt](https://github.com/zellij-org/zellij/files/6358168/log.txt)

**Comment by luqmanishere** [comment] 2021-04-22 16:11
Here's mine when opening neovim.

[log.txt](https://github.com/zellij-org/zellij/files/6359691/log.txt)

Hope this helps.

**Comment by a-kenji** [comment] 2021-04-22 16:45
Thank you! Yes that is very valuable!

**Comment by lunush** [comment] 2021-04-24 04:40
Hi @a-kenji, here is my log file. It is identical to yours:
```
Unhandled csi: t->[22, 0, 0]
Unhandled csi: t->[22, 0, 0]
Unhandled csi: t->[23, 0, 0]
Unhandled csi: t->[23, 0, 0]
```

**Comment by matu3ba** [comment] 2021-05-03 12:58
@lunush identical for me.

**Comment by N4tus** [comment] 2021-05-06 19:01
im using zellij (0.7.0) in alacritty with wsl2 and neovim does display colors but the curser is not correctly rendered (always a block). Also on the right most column there are fake cursers flickering whenever i press a key.

**Comment by imsnif** [comment] 2021-05-11 09:55
There are quite a few reports in this one issue, so it's a little hard to keep track of all of them. But I *think* all if not most of them should be fixed in version `0.9.0`. Could you please give it a try?

**Comment by a-kenji** [comment] 2021-05-11 10:08
I still have that issue on `0.9.0`.
My log.txt:

```
Unhandled csi: t->[22, 0, 0]
Unhandled csi: t->[22, 0, 0]
Unhandled csi: t->[23, 0, 0]
Unhandled csi: t->[23, 0, 0]
```

**Comment by a-kenji** [comment] 2021-05-11 11:01
Sure! 
I think the colors are OK, but my theme didn't seem to have an issue before, if I see it correctly:
![image](https://user-images.githubusercontent.com/65275785/117805042-cb250800-b258-11eb-8903-4635e2353597.png)

Left is `0.9.0`, right is `0.8.0`

[zellij-11.log](https://github.com/zellij-org/zellij/files/6458676/zellij-11.log)
[zellij-12.log](https://github.com/zellij-org/zellij/files/6458677/zellij-12.log)
[zellij-13.log](https://github.com/zellij-org/zellij/files/6458678/zellij-13.log)

**Comment by a-kenji** [comment] 2021-05-11 13:56
> I can't seem to reproduce the issue with the log files you attached... if you cat zellij-11.log do you see the issue? 

No. It seems to error out if I cat the log.

>This is with the cursor turning into a line, right?

Yes!

>I could also do with reproducing this with neovim itself if it's easier, but the version I have doesn't do this. Is it some sort of plugin, or?

Good thinking! I tried it with `--no-plugins` , but to no avail.
This is my version: 
```
NVIM v0.5.0-dev
Build type: Release
LuaJIT 2.1.0-beta3
Compilation:
Compiled by nixbld
```

**Comment by luqmanishere** [comment] 2021-05-12 04:08
Version 0.9.0 has fixed the colors and the line cursor for me. Thanks devs!

**Comment by a-kenji** [comment] 2021-05-12 07:36
@imsnif 
It is fixed now! Thanks for all the work.
Maybe it was an issue with the neovim release.

**Comment by imsnif** [comment] 2021-05-12 07:41
Awesome :) Closing this issue. If anyone of the commenters here (or someone else) still experiences one of the problems here, please tag me and I'll re-open it and look into it.

**Comment by hbiel** [comment] 2022-02-23 14:42
@imsnif

I'm adopting zellij to my workflow since yesterdays 0.25.0 release and am facing the cursor issue in nvim. Without zellij the cursor changes when entering insert mode. Using zellij it's always drawn as a block.

I'am on Windows using wsl2 and Windows Terminal.
Neovim was on the latest nightly build.

Let me know if you need more information or when I can test something on my end to fix this.

Thank you!

**Comment by hbiel** [comment] 2022-02-23 19:22
Thanks for pointing me to the issue template! For the debug log i did the following steps:

1. zellij --debug
2. nvim
3. entering insert mode
4. typed in some text

[zellij.log](https://github.com/zellij-org/zellij/files/8127210/zellij.log)
[zellij-9.log](https://github.com/zellij-org/zellij/files/8127211/zellij-9.log)

❯ zellij --version
zellij 0.25.0
❯ tput lines
30
❯ tput cols
120
❯ uname -av
Linux NBFQ3455 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
❯ nvim --version
NVIM v0.7.0-dev+1130-g11f7aeed7

Windows Terminal Preview Version: 1.10.1933.0

This said i had it only happening on my work pc so far. I also tested it on my private pc and there its working.
As the Windows Terminal seems is an older version on this machine i will try to update it and see if this helps.

**Comment by hbiel** [comment] 2022-02-24 21:40
@imsnif You can probably close this issue again.

I found the problem within my configuration: I'am currently using [zsh4humans](https://github.com/romkatv/zsh4humans) which automatically starts the shell in tmux. This was not obvious to me because the tmux statusbar was hidden.

I have now disabled this behaviour completely and everything works fine now!

**Closed** 2022-02-28 07:02 UTC
Labels: bug, compatibility
