### ISSUE TITLE
Error: thread 'screen' panicked at 'called `Option::unwrap()` on a `None` value': zellij-server/src/screen.rs:226

### ISSUE THREAD

**Issue by happysalada** [zellij-org/zellij#805] opened 2021-10-26 04:54 UTC
Thank you for taking the time to file this issue! Please follow the instructions and fill the missing parts below the instructions, if it is meaningful. Try to be brief and concise.

Please attach the files that were created in `/tmp/zellij-1000/zellij-log/` to the extent you are comfortable with.

**Basic information**

`zellij --version`: 0.18.1
`tput lines`:
`tput cols`:
`uname -av` or `ver`(Windows): Darwin yt 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64

List of programs you interact with as, `PROGRAM --version`: output cropped meaningful, for example:
`alacritty --version`: alacritty 0.9.0

**Further information**
This happens upon trying to close a tab. When hitting the `x` of closing a particular tab, sometimes I just get the crash

I can't reproduce reliably, this bug happens just from time to time. The logs without the debug flag contain the following
```
INFO   |zellij_client            | 2021-10-24 21:00:29.051 [main      ] [zellij-client/src/lib.rs:107]: Starting Zellij client! 
INFO   |zellij_server            | 2021-10-24 21:00:29.065 [main      ] [zellij-server/src/lib.rs:174]: Starting Zellij server! 
INFO   |zellij_server::wasm_vm   | 2021-10-24 21:00:29.122 [wasm      ] [zellij-server/src/wasm_vm.rs:73]: Wasm main thread starts 
INFO   |zellij_server::wasm_vm   | 2021-10-25 22:17:59.637 [wasm      ] [zellij-server/src/wasm_vm.rs:148]: Bye from plugin 4 
INFO   |zellij_server::wasm_vm   | 2021-10-25 22:17:59.672 [wasm      ] [zellij-server/src/wasm_vm.rs:148]: Bye from plugin 5 
INFO   |zellij_server::wasm_vm   | 2021-10-25 22:18:00.630 [wasm      ] [zellij-server/src/wasm_vm.rs:148]: Bye from plugin 2 
INFO   |zellij_server::wasm_vm   | 2021-10-25 22:18:00.640 [wasm      ] [zellij-server/src/wasm_vm.rs:148]: Bye from plugin 3 
INFO   |zellij_server::wasm_vm   | 2021-10-25 22:37:41.320 [wasm      ] [zellij-server/src/wasm_vm.rs:148]: Bye from plugin 8 
INFO   |zellij_server::wasm_vm   | 2021-10-25 22:37:41.323 [wasm      ] [zellij-server/src/wasm_vm.rs:148]: Bye from plugin 9 
INFO   |zellij_server::wasm_vm   | 2021-10-26 13:48:34.340 [wasm      ] [zellij-server/src/wasm_vm.rs:148]: Bye from plugin 10 
INFO   |zellij_server::wasm_vm   | 2021-10-26 13:48:34.350 [wasm      ] [zellij-server/src/wasm_vm.rs:148]: Bye from plugin 11 
INFO   |zellij_server::wasm_vm   | 2021-10-26 13:48:35.704 [wasm      ] [zellij-server/src/wasm_vm.rs:148]: Bye from plugin 12 
INFO   |zellij_server::wasm_vm   | 2021-10-26 13:48:35.710 [wasm      ] [zellij-server/src/wasm_vm.rs:148]: Bye from plugin 13 
INFO   |zellij_server::wasm_vm   | 2021-10-26 13:48:38.751 [wasm      ] [zellij-server/src/wasm_vm.rs:155]: wasm main thread exits 
```

**Comment by mikeevmm** [comment] 2022-02-01 22:15
Hey, I'm getting the same message, and I've figured out it happens if I manage to type into the terminal while my .bashrc is still sourcing; i.e., before the `zellij` command is actually executed.

(My PC isn't the fastest :) )

Here's the full trace:

```
Error: thread 'screen' panicked at 'called `Option::unwrap()` on a `None` value': /home/miguelmurca/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.24.0/src/screen.rs:1010
   0: zellij_utils::errors::handle_panic
   1: std::panicking::rust_panic_with_hook
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:628:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:519:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:139:18
   4: rust_begin_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   5: core::panicking::panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
   6: core::panicking::panic
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:50:5
   7: zellij_server::screen::screen_thread_main
   8: std::sys_common::backtrace::__rust_begin_short_backtrace
   9: core::ops::function::FnOnce::call_once{{vtable.shim}}
  10: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/boxed.rs:1691:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/boxed.rs:1691:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys/unix/thread.rs:106:17
  11: start_thread
  12: clone
```

**Comment by raphCode** [comment] 2022-02-22 01:06
I can reproduce (for example with bash):
- `echo sleep 10 >> .bashrc`
- `bash`
- In the 10 second delay, type `zellij`, press `Enter`, then type at least 1 more letter
- After the `.bashrc` finished sourcing, zellij gets executed and crashes instantly

Don't forget to remove the delay from your .bashrc again, this gets pretty annoying :D

**Comment by raphCode** [comment] 2022-03-11 22:27
The second kind of crash with stdin / bashrc seems to be reported in a new issue: https://github.com/zellij-org/zellij/issues/1134

This leaves only the original crash from the first message to be discussed here.

**Comment by imsnif** [comment] 2022-03-25 09:37
Both of these are now fixed in main

**Closed by imsnif** 2022-03-25 09:37 UTC
Labels: bug, stability
