### ISSUE TITLE
Multisession state persistence bug?

### ISSUE THREAD

**Issue by alekspickle** [zellij-org/zellij#963] opened 2021-12-22 11:57 UTC
**Basic information**
`zellij --version`: zellij 0.23.0
`tput lines`: 60
`tput cols`: 125
`uname -av`: Linux pickle 5.11.0-37-generic #41~20.04.2-Ubuntu SMP Fri Sep 24 09:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

`cargo 1.56.0 (4ed5d137b 2021-10-04)`
`rustc 1.56.1 (09c42c458 2021-10-18)`
`git version 2.33.0`
`zsh 5.8 (x86_64-ubuntu-linux-gnu)`

**Further information**
I joined my session I used another terminal tab to connect with so I see how multisession is working. And it displayed as expected I guess: I saw whitespace with colored background on tab of another user. 
When I disconnected it was gone. But day later I reconnect to this session and see this colored whitespace but no users attached to it. When I attached and detached from other tab it was gone. Looks like some state persistence?

The only suspicious log I found in `zellij.log` is:
`WARN   |zellij_server::panes::gri| 2021-12-22 12:51:51.896 [screen    ] [/root/.cargo/registry/src/github.com-1ecc6299db9
    ec823/zellij-server-0.23.0/src/panes/grid.rs:2053]: Unhandled csi: p->[12]`

**Comment by imsnif** [comment] 2021-12-22 12:01
So, just to make sure, you:
1. Started a session
2. Connected to it with another user
3. The UI displayed the other user in the tab as expected
4. Disconnected the other user
5. The UI displayed no other users in the tab as expected
6. Disconnected the first user
7. Reconnected the first user and the UI indicated there are two users connected?

**Comment by alekspickle** [comment] 2021-12-22 13:42
Yep

**Comment by jovandeginste** [comment] 2021-12-22 17:43
I saw the same behaviour, didn't test the exact steps yet to reproduce. I'm sure I'm the single user of that session, though I see a panel title "My focus AND [ ]" (with some pinkish square).

This square seemed to move with me when I switched tabs, so maybe there is something wrong when switching tabs?

So to be clear: I never used the same session with two simultaneous users, but detach + re-attached.

**Comment by jovandeginste** [comment] 2021-12-23 07:49
Steps to reproduce for me are:

- start initial zellij session with `attach --create`
```bash
zellij attach --create
```
- create new tab
- detach session
- rerun above command

Pane title is: `─┤ MY FOCUS AND: X ├──` (where X is a magenta square)

![image](https://user-images.githubusercontent.com/3170771/147206593-21468fe6-df8f-4476-8d45-3c56b3d5d039.png)

**Comment by imsnif** [comment] 2021-12-23 09:29
Right, I just issued a fix for this. If one of you wants to test out this musl binary to make sure, that'll be great (though no biggie, I'm pretty sure I got the issue).
[zellij-musl.tar.gz](https://github.com/zellij-org/zellij/files/7768192/zellij-musl.tar.gz)

**Comment by jovandeginste** [comment] 2021-12-23 10:23
Quick test confirms this is fixed for me.

**Comment by jovandeginste** [comment] 2021-12-24 08:20
Re-attaching this morning to my session from yesterday left me with a weird state: I can switch tabs, the other shortcuts seem to work, but the actual content doesn't change. I did not check what other changes were committed since the white-space issues got fixed, but maybe the fix for this issue here is causing this?

Eg. switching tabs changes the top bar, reflecting this change, but the actual panes (and pane content) remain the same.

I tried detaching en re-attaching, but this doesn't change anything.... If I detach on a different tab, and then re-attach, I'm back on the first tab.

**Comment by jovandeginste** [comment] 2021-12-24 08:23
So, right after posting this comment, I did a wild thing: I created a new tab (in that "blocked" session). This actually created a new tab, focussed on it, and everything just worked again as it should. I also saw (at least some of) the other steps I did, reflected in the panes where I did them (blindly then).

**Comment by imsnif** [comment] 2021-12-24 08:44
Oi man, I'm sorry to hear that! I am unfortunately not managing to recreate this. Are you working with the musl I attached here? Can you recreate this from scratch, or is it just dependent on something that happened in the long running session?

**Comment by jovandeginste** [comment] 2021-12-24 09:43
Actually, no. This was on a different system where I'm still using the binary with the whitespace fixes. Not the one you added here. Sorry for the confusion.

Could it be that your changes here fix the issue I was now describing?

**Comment by imsnif** [comment] 2021-12-24 09:44
> Could it be that your changes here fix the issue I was now describing?
Definitely, yes. Though I can also imagine them causing this issue, if I'm being fair.

**Comment by jovandeginste** [comment] 2021-12-24 09:46
Well, I'm sure I was not using the binary attached here: 

```bash
$ md5sum ~/bin/zellij                                                                                                                                                                                                 
d2d09928dd121871af4ba32c0297d70c  ~/bin/zellij
```

**Comment by imsnif** [comment] 2021-12-24 10:02
Happy new year to you as well! I hope you have a good break, and thanks for all your help and feedback.

**Comment by raphCode** [comment] 2022-04-28 12:26
I think this is fixed and can be closed?

**Closed** 2022-04-28 13:40 UTC
Labels: bug

**Comment by alekspickle** [comment] 2022-04-28 13:59
I've stopped experiencing this circa 0.24v so I think so!
