### ISSUE TITLE
Open neovim in zellij, there are black lines not fully rendered

### ISSUE THREAD

**Issue by liaohui5** [zellij-org/zellij#1691] opened 2022-08-25 16:18 UTC
Open neovim in zellij, there are black lines not fully rendered
Also, I have this problem whether I open it with Alacritty or kitty or iTerm2
![image](https://user-images.githubusercontent.com/29266093/186714811-79779f86-ad86-4f59-b245-263f2e3781cf.png)
![image](https://user-images.githubusercontent.com/29266093/186715343-0d1fb82e-7b30-4ba5-963c-64a62b2eb36b.png)
![image](https://user-images.githubusercontent.com/29266093/186716603-f65c3a3d-cdd2-436d-bd5b-9289e838ef86.png)

## Basic information

`zellij --version`: 0.31.1
`shell`:  zsh
`OS`: MacOS  Monterey Version 12.4 (21F79) MacBook Pro (16-inch, 2019)
`nvim --version`:  0.7.2 Build type:  Release [commit](https://github.com/neovim/neovim/commit/e8ee6733926db83ef216497a1d660a173184ff39)
`alacritty --version`: alacritty 0.10.1 (2844606)
`kitty --version`: alacritty 0.10.1 (2844606)
`iterm2 version`: Build 3.4.16

## Reproduction steps
1. open terminal kitty
2. open zellij
3. open neovim

Need provide more infomation form me?

**Comment by imsnif** [comment] 2022-08-26 07:40
Hey @liaohui5 - I can't reproduce this issue with my neovim. Could you please try recreating this with the latest version (currently 0.31.3) and if it still happens attach the debug info as specified here: https://github.com/zellij-org/zellij/blob/main/.github/ISSUE_TEMPLATE/bug_report.md ? That way I'll be able to reproduce the issue for sure. Thanks!

**Comment by liaohui5** [comment] 2022-08-30 09:46
`alacritty`: alacritty 0.10.1 (2844606)
`shell`: zsh
`neovim`:  0.7.2 Build type: Release

I upgraded zellij to version 0.3.2,but the problem still exists
I deleted old log files, then execute `zellij --debug` command,
I get log(`/tmp/zellij-502/zellij-log/zellij.log`) content like this

```
INFO   |zellij_client            | 2022-08-30 17:32:05.580 [main      ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-client-0.31.3/src/lib.rs:129]: Starting Zellij client! 
INFO   |zellij_server            | 2022-08-30 17:32:05.586 [main      ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/lib.rs:195]: Starting Zellij server! 
INFO   |zellij_server::wasm_vm   | 2022-08-30 17:32:05.640 [wasm      ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/wasm_vm.rs:87]: Wasm main thread starts 
WARN   |zellij_server::panes::gri| 2022-08-30 17:32:06.259 [screen    ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/panes/grid.rs:2207]: Unhandled osc: [[49, 51, 51, 55], [82, 101, 109, 111, 116, 101, 72, 111, 115, 116, 61, 108, 105, 97, 111, 104, 117, 105, 53, 64, 77, 97, 99, 66, 111, 111, 107, 46, 108, 111, 99, 97, 108]] 
WARN   |zellij_server::panes::gri| 2022-08-30 17:32:06.259 [screen    ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/panes/grid.rs:2207]: Unhandled osc: [[49, 51, 51, 55], [67, 117, 114, 114, 101, 110, 116, 68, 105, 114, 61, 47, 116, 109, 112]] 
WARN   |zellij_server::panes::gri| 2022-08-30 17:32:06.260 [screen    ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/panes/grid.rs:2207]: Unhandled osc: [[49, 51, 51, 55], [83, 104, 101, 108, 108, 73, 110, 116, 101, 103, 114, 97, 116, 105, 111, 110, 86, 101, 114, 115, 105, 111, 110, 61, 49, 51], [115, 104, 101, 108, 108, 61, 122, 115, 104]] 
WARN   |zellij_server::panes::gri| 2022-08-30 17:32:06.266 [screen    ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/panes/grid.rs:2207]: Unhandled osc: [[49], [47, 116, 109, 112]] 
WARN   |zellij_server::panes::gri| 2022-08-30 17:32:06.304 [screen    ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/panes/grid.rs:2207]: Unhandled osc: [[49, 51, 51], [68], [48]] 
WARN   |zellij_server::panes::gri| 2022-08-30 17:32:06.306 [screen    ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/panes/grid.rs:2207]: Unhandled osc: [[49, 51, 51, 55], [82, 101, 109, 111, 116, 101, 72, 111, 115, 116, 61, 108, 105, 97, 111, 104, 117, 105, 53, 64, 77, 97, 99, 66, 111, 111, 107, 46, 108, 111, 99, 97, 108]] 
WARN   |zellij_server::panes::gri| 2022-08-30 17:32:06.306 [screen    ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/panes/grid.rs:2207]: Unhandled osc: [[49, 51, 51, 55], [67, 117, 114, 114, 101, 110, 116, 68, 105, 114, 61, 47, 116, 109, 112]] 
WARN   |zellij_server::panes::gri| 2022-08-30 17:32:06.310 [screen    ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/panes/grid.rs:2207]: Unhandled osc: [[49, 51, 51], [65]] 
WARN   |zellij_server::panes::gri| 2022-08-30 17:32:06.310 [screen    ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/panes/grid.rs:2207]: Unhandled osc: [[49, 51, 51], [66]] 
WARN   |zellij_server::panes::gri| 2022-08-30 17:32:06.312 [screen    ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/panes/grid.rs:2744]: Unhandled esc_dispatch: 61->[] 
WARN   |zellij_server::panes::gri| 2022-08-30 17:32:08.012 [screen    ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/panes/grid.rs:2744]: Unhandled esc_dispatch: 62->[] 
WARN   |zellij_server::panes::gri| 2022-08-30 17:32:08.013 [screen    ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/panes/grid.rs:2207]: Unhandled osc: [[49], [110, 118, 105, 109]] 
WARN   |zellij_server::panes::gri| 2022-08-30 17:32:08.014 [screen    ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/panes/grid.rs:2207]: Unhandled osc: [[49, 51, 51], [67], []] 
WARN   |zellij_server::panes::gri| 2022-08-30 17:32:08.032 [screen    ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/panes/grid.rs:2744]: Unhandled esc_dispatch: 61->[] 
WARN   |zellij_server::panes::gri| 2022-08-30 17:32:11.188 [screen    ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/panes/grid.rs:2744]: Unhandled esc_dispatch: 62->[] 
WARN   |zellij_server::panes::gri| 2022-08-30 17:32:11.197 [screen    ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/panes/grid.rs:2207]: Unhandled osc: [[49], [47, 116, 109, 112]] 
WARN   |zellij_server::panes::gri| 2022-08-30 17:32:11.235 [screen    ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/panes/grid.rs:2207]: Unhandled osc: [[49, 51, 51], [68], [48]] 
WARN   |zellij_server::panes::gri| 2022-08-30 17:32:11.237 [screen    ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/panes/grid.rs:2207]: Unhandled osc: [[49, 51, 51, 55], [82, 101, 109, 111, 116, 101, 72, 111, 115, 116, 61, 108, 105, 97, 111, 104, 117, 105, 53, 64, 77, 97, 99, 66, 111, 111, 107, 46, 108, 111, 99, 97, 108]] 
WARN   |zellij_server::panes::gri| 2022-08-30 17:32:11.237 [screen    ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/panes/grid.rs:2207]: Unhandled osc: [[49, 51, 51, 55], [67, 117, 114, 114, 101, 110, 116, 68, 105, 114, 61, 47, 116, 109, 112]] 
WARN   |zellij_server::panes::gri| 2022-08-30 17:32:11.242 [screen    ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/panes/grid.rs:2207]: Unhandled osc: [[49, 51, 51], [65]] 
WARN   |zellij_server::panes::gri| 2022-08-30 17:32:11.242 [screen    ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/panes/grid.rs:2207]: Unhandled osc: [[49, 51, 51], [66]] 
WARN   |zellij_server::panes::gri| 2022-08-30 17:32:11.243 [screen    ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/panes/grid.rs:2744]: Unhandled esc_dispatch: 61->[] 
INFO   |zellij_client            | 2022-08-30 17:32:12.056 [main      ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-client-0.31.3/src/lib.rs:394]: Bye from Zellij! 
INFO   |zellij_server::wasm_vm   | 2022-08-30 17:32:12.056 [wasm      ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/wasm_vm.rs:165]: Bye from plugin 0 
ERROR  |zellij_utils::errors     | 2022-08-30 17:32:12.057 [screen    ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-utils-0.31.3/src/errors.rs:94]: Panic occured:
             thread: screen
             location: At /Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/screen.rs:945:14
             message: failed to receive event on channel: RecvError 
INFO   |zellij_server::wasm_vm   | 2022-08-30 17:32:12.058 [wasm      ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/wasm_vm.rs:165]: Bye from plugin 1 
INFO   |zellij_server::wasm_vm   | 2022-08-30 17:32:12.061 [wasm      ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/wasm_vm.rs:213]: wasm main thread exits 

```

**Comment by liaohui5** [comment] 2022-08-30 09:48
> Hey @liaohui5 - I can't reproduce this issue with my neovim. Could you please try recreating this with the latest version (currently 0.31.3) and if it still happens attach the debug info as specified here: https://github.com/zellij-org/zellij/blob/main/.github/ISSUE_TEMPLATE/bug_report.md ? That way I'll be able to reproduce the issue for sure. Thanks!

I upgraded zellij to version 0.3.2,but the problem still exists
I deleted old log files, then execute `zellij --debug` command,
I get log(`/tmp/zellij-502/zellij-log/zellij.log`) content like this

`alacritty`: alacritty 0.10.1 (2844606)
`shell`: zsh
`neovim`:  0.7.2 Build type: Release

```
INFO   |zellij_client            | 2022-08-30 17:32:05.580 [main      ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-client-0.31.3/src/lib.rs:129]: Starting Zellij client! 
INFO   |zellij_server            | 2022-08-30 17:32:05.586 [main      ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/lib.rs:195]: Starting Zellij server! 
INFO   |zellij_server::wasm_vm   | 2022-08-30 17:32:05.640 [wasm      ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/wasm_vm.rs:87]: Wasm main thread starts 
WARN   |zellij_server::panes::gri| 2022-08-30 17:32:06.259 [screen    ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/panes/grid.rs:2207]: Unhandled osc: [[49, 51, 51, 55], [82, 101, 109, 111, 116, 101, 72, 111, 115, 116, 61, 108, 105, 97, 111, 104, 117, 105, 53, 64, 77, 97, 99, 66, 111, 111, 107, 46, 108, 111, 99, 97, 108]] 
WARN   |zellij_server::panes::gri| 2022-08-30 17:32:06.259 [screen    ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/panes/grid.rs:2207]: Unhandled osc: [[49, 51, 51, 55], [67, 117, 114, 114, 101, 110, 116, 68, 105, 114, 61, 47, 116, 109, 112]] 
WARN   |zellij_server::panes::gri| 2022-08-30 17:32:06.260 [screen    ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/panes/grid.rs:2207]: Unhandled osc: [[49, 51, 51, 55], [83, 104, 101, 108, 108, 73, 110, 116, 101, 103, 114, 97, 116, 105, 111, 110, 86, 101, 114, 115, 105, 111, 110, 61, 49, 51], [115, 104, 101, 108, 108, 61, 122, 115, 104]] 
WARN   |zellij_server::panes::gri| 2022-08-30 17:32:06.266 [screen    ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/panes/grid.rs:2207]: Unhandled osc: [[49], [47, 116, 109, 112]] 
WARN   |zellij_server::panes::gri| 2022-08-30 17:32:06.304 [screen    ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/panes/grid.rs:2207]: Unhandled osc: [[49, 51, 51], [68], [48]] 
WARN   |zellij_server::panes::gri| 2022-08-30 17:32:06.306 [screen    ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/panes/grid.rs:2207]: Unhandled osc: [[49, 51, 51, 55], [82, 101, 109, 111, 116, 101, 72, 111, 115, 116, 61, 108, 105, 97, 111, 104, 117, 105, 53, 64, 77, 97, 99, 66, 111, 111, 107, 46, 108, 111, 99, 97, 108]] 
WARN   |zellij_server::panes::gri| 2022-08-30 17:32:06.306 [screen    ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/panes/grid.rs:2207]: Unhandled osc: [[49, 51, 51, 55], [67, 117, 114, 114, 101, 110, 116, 68, 105, 114, 61, 47, 116, 109, 112]] 
WARN   |zellij_server::panes::gri| 2022-08-30 17:32:06.310 [screen    ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/panes/grid.rs:2207]: Unhandled osc: [[49, 51, 51], [65]] 
WARN   |zellij_server::panes::gri| 2022-08-30 17:32:06.310 [screen    ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/panes/grid.rs:2207]: Unhandled osc: [[49, 51, 51], [66]] 
WARN   |zellij_server::panes::gri| 2022-08-30 17:32:06.312 [screen    ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/panes/grid.rs:2744]: Unhandled esc_dispatch: 61->[] 
WARN   |zellij_server::panes::gri| 2022-08-30 17:32:08.012 [screen    ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/panes/grid.rs:2744]: Unhandled esc_dispatch: 62->[] 
WARN   |zellij_server::panes::gri| 2022-08-30 17:32:08.013 [screen    ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/panes/grid.rs:2207]: Unhandled osc: [[49], [110, 118, 105, 109]] 
WARN   |zellij_server::panes::gri| 2022-08-30 17:32:08.014 [screen    ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/panes/grid.rs:2207]: Unhandled osc: [[49, 51, 51], [67], []] 
WARN   |zellij_server::panes::gri| 2022-08-30 17:32:08.032 [screen    ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/panes/grid.rs:2744]: Unhandled esc_dispatch: 61->[] 
WARN   |zellij_server::panes::gri| 2022-08-30 17:32:11.188 [screen    ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/panes/grid.rs:2744]: Unhandled esc_dispatch: 62->[] 
WARN   |zellij_server::panes::gri| 2022-08-30 17:32:11.197 [screen    ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/panes/grid.rs:2207]: Unhandled osc: [[49], [47, 116, 109, 112]] 
WARN   |zellij_server::panes::gri| 2022-08-30 17:32:11.235 [screen    ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/panes/grid.rs:2207]: Unhandled osc: [[49, 51, 51], [68], [48]] 
WARN   |zellij_server::panes::gri| 2022-08-30 17:32:11.237 [screen    ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/panes/grid.rs:2207]: Unhandled osc: [[49, 51, 51, 55], [82, 101, 109, 111, 116, 101, 72, 111, 115, 116, 61, 108, 105, 97, 111, 104, 117, 105, 53, 64, 77, 97, 99, 66, 111, 111, 107, 46, 108, 111, 99, 97, 108]] 
WARN   |zellij_server::panes::gri| 2022-08-30 17:32:11.237 [screen    ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/panes/grid.rs:2207]: Unhandled osc: [[49, 51, 51, 55], [67, 117, 114, 114, 101, 110, 116, 68, 105, 114, 61, 47, 116, 109, 112]] 
WARN   |zellij_server::panes::gri| 2022-08-30 17:32:11.242 [screen    ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/panes/grid.rs:2207]: Unhandled osc: [[49, 51, 51], [65]] 
WARN   |zellij_server::panes::gri| 2022-08-30 17:32:11.242 [screen    ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/panes/grid.rs:2207]: Unhandled osc: [[49, 51, 51], [66]] 
WARN   |zellij_server::panes::gri| 2022-08-30 17:32:11.243 [screen    ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/panes/grid.rs:2744]: Unhandled esc_dispatch: 61->[] 
INFO   |zellij_client            | 2022-08-30 17:32:12.056 [main      ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-client-0.31.3/src/lib.rs:394]: Bye from Zellij! 
INFO   |zellij_server::wasm_vm   | 2022-08-30 17:32:12.056 [wasm      ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/wasm_vm.rs:165]: Bye from plugin 0 
ERROR  |zellij_utils::errors     | 2022-08-30 17:32:12.057 [screen    ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-utils-0.31.3/src/errors.rs:94]: Panic occured:
             thread: screen
             location: At /Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/screen.rs:945:14
             message: failed to receive event on channel: RecvError 
INFO   |zellij_server::wasm_vm   | 2022-08-30 17:32:12.058 [wasm      ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/wasm_vm.rs:165]: Bye from plugin 1 
INFO   |zellij_server::wasm_vm   | 2022-08-30 17:32:12.061 [wasm      ] [/Users/liaohui5/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.31.3/src/wasm_vm.rs:213]: wasm main thread exits 

```

**Comment by liaohui5** [comment] 2022-08-30 10:03
@imsnif Oh, sorry, I may not have made it clear earlier,
alacritty background color is not the same as neovim's background color
Hope this info helps you reproduce the bug

**Comment by imsnif** [comment] 2022-09-02 14:25
@liaohui5 - I still wasn't able to reproduce this, I'm afraid.

If you could follow the instructions under "In Case of Graphical or Performance Issues" in https://github.com/zellij-org/zellij/blob/main/.github/ISSUE_TEMPLATE/bug_report.md, and attach the relevant logs, it will allow me to recreate the issue directly - without relying on neovim or my local environment.

I think this will save us a lot of time and back-and-forth trying to figure out exactly how to recreate this. Thanks!

**Comment by imsnif** [comment] 2022-09-09 07:57
I'm closing this issue for now. @liaohui5 - if you'd like to provide the log files please attach them here, ping me and I'll reopen so we can investigate further.

**Closed by imsnif** 2022-09-09 07:57 UTC
Labels: bug

**Comment by liaohui5** [comment] 2022-09-09 11:57
> I'm closing this issue for now. @liaohui5 - if you'd like to provide the log files please attach them here, ping me and I'll reopen so we can investigate further.

I found the problem, sorry, it's my neovim configuration problem, not zellij's problem
When I reinstall neovim without any plugins, I don't have this problem
But I still don't know which plugin it is
Thank you very much for your help, you are a very good developer

**Comment by imsnif** [comment] 2022-09-09 12:00
@liaohui5 - if you find out more, please ping me in this issue. This can still be a Zellij issue and I'd be happy to fix it if that's the case!
