### ISSUE TITLE
Feature Request: Dump current layout 

### ISSUE THREAD

**Issue by Kushagra-0801** [zellij-org/zellij#1741] opened 2022-09-19 12:33 UTC
I would like a way to write something like `zellij --dump-layout <SESSION>` and have a layout file ready to be used the next time.
This will make it easy to make custom layouts (open a session, mess around, dump the layout, profit) and make it easy to learn how the layout config works (do something, dump layout, compare with old, learn, profit).

As a personal use case, it will make it simple to write a script that stores my current layout to file and reopens it on next boot.

**Comment by har7an** [comment] 2022-09-21 07:06
Hi and thanks for reporting this!

I think this is a duplicate of #381, so I will close this issue for now. Fell free to join the discussion there, or to reopen this issue if you think it is a separate feature request.

**Closed by har7an** 2022-09-21 07:06 UTC
