### ISSUE TITLE
(feature request) Pane focus on mouse hover

### ISSUE THREAD

**Issue by dougg0k** [zellij-org/zellij#3131] opened 2024-02-12 12:20 UTC
Hi,

Is there a setting to activate this behavior?

If not, that would be useful in some situations. 

tmux, terminator and wezterm seem to have that by activating a setting.

**Comment by imsnif** [comment] 2024-02-12 13:00
Hi - thanks for opening the issue. This is a duplicate of: https://github.com/zellij-org/zellij/issues/1679

**Closed by imsnif** 2024-02-12 13:00 UTC
