### ISSUE TITLE
Thread 'pty' panicked

### ISSUE THREAD

**Issue by bombusfragrans** [zellij-org/zellij#1751] opened 2022-09-24 09:43 UTC
As requested by the error message

- when  does it occur: `ash zellij`
- zellij version; zellij 0.29.1
- environment: alpine/latest running as podman container
- `uname -a` inside container: `Linux dc80d9f5e3d5 5.15.65-1-MANJARO #1 SMP PREEMPT Mon Sep 5 10:15:47 UTC 2022 x86_64 Linux`
- `stty size`:
```ash
stty -a
speed 38400 baud; rows 52; columns 191; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R; werase = ^W; lnext = ^V; flush = ^O;
min = 1; time = 0;
-parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff -iuclc -ixany -imaxbel -iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke -flusho -extproc
```

**ERROR message:**
```ash
~ # zellij

Error occurred in server:

  × Thread 'pty' panicked.
  ├─▶ Originating Thread(s)
  │   	1. ipc_server: NewClient
  │   	2. pty_thread: NewTab
  │   
  ├─▶ At zellij-server/src/pty.rs:282:54
  ╰─▶ Could not find the SHELL variable: NotPresent
  help: If you are seeing this message, it means that something went wrong.
        Please report this error to the github issue.
        (https://github.com/zellij-org/zellij/issues)
        
        Also, if you want to see the backtrace, you can set the `RUST_BACKTRACE` environment variable to `1`.

1;rgb:1e1e/1f1f/2929f8f8/f2f2
```
I would post content of `/tmp/zellij-1000/zellij-log/`, but apparently has not been created at that point (/tmp empty)

Awesome software! Runs fine natively on Manjaro host (installed from official repo). Hope it helps...

**Comment by imsnif** [comment] 2022-09-24 09:45
Hey, I'm pretty sure this was fixed in the latest version (at this point 0.31.4) - could you give it a try?

**Comment by ditsuke** [comment] 2022-10-02 17:00
Can reproduce on a fresh Zellij installation in the `ubuntu` docker image.

**Comment by raphCode** [comment] 2022-11-23 09:55
This should be fixed by https://github.com/zellij-org/zellij/pull/1769 and is in the next release.
Please comment if the issue is still present.

**Closed by raphCode** 2022-11-23 09:55 UTC
Labels: bug
