### ISSUE TITLE
Feature request: support working directory in layout configuration

### ISSUE THREAD

**Issue by fpauser** [zellij-org/zellij#1352] opened 2022-04-27 10:26 UTC
Right now the layout config only supports the options `direction`, `pane_name`, `parts`, `split_size`, `run`, `borderless` and `focus`.
In order to set the default working directory for a part I tried to use `run` to change the current directory of that part:

```
run:
  command: {cmd: cd, args: ["~/path/to/working/directory"]}
```

But this completely closes the part, as `run` currently only works with long-running commands. Besides strange `run` behavior wouldn't it be better to support a new option `working_directory` or `path` or something similar? Another way would be to fix `run` to allow executing commands like `cd`.

**Comment by a-kenji** [comment] 2022-04-27 10:29
This is a duplicate of #604.

**Comment by fpauser** [comment] 2022-04-27 11:30
Closing as it is a duplicate.

Work around for bash:

```yml
run:
  command: {cmd: bash, args: ["-c", "cd $HOME/path/to/working/dir && exec bash"]}
```

**Closed** 2022-04-27 11:30 UTC
Labels: duplicate
