### ISSUE TITLE
Session manager ui is very slow to load session list

### ISSUE THREAD

**Issue by rbingham** [zellij-org/zellij#2959] opened 2023-11-23 05:19 UTC
## Description
When loading the session manager ui, it takes ~30s to load the session list when attaching or switching to a session. I am unable to switch sessions until the session list has loaded. This happens with both my custom config / layout and the default config / layout.

### System Info
`zellij --version: 0.39.1`
`stty size: 55 230`
`alacritty --version: alacritty 0.12.3 (5efb069)`
`uname -av: Darwin hostname.lan 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:45 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6020 arm64`

### Config files
[config.kdl](https://github.com/zellij-org/zellij/files/13446233/config.txt)
[default.kdl](https://github.com/zellij-org/zellij/files/13446234/default.txt)

### Log files
[zellij-11.log](https://github.com/zellij-org/zellij/files/13446185/zellij-11.log)
[zellij.log](https://github.com/zellij-org/zellij/files/13446186/zellij.log)

[Screen recording](https://github.com/zellij-org/zellij/assets/7032804/45e2c0a7-6ed6-4df2-9390-e208a2a1780e)

**Comment by imsnif** [comment] 2023-11-23 08:01
Hey, thanks for reporting this! This is an issue with the latest patch version and is already fixed in main: https://github.com/zellij-org/zellij/pull/2951

**Comment by imsnif** [comment] 2023-11-23 13:35
I forgot to mention: as a workaround until the patch is released, you can add `session_serialization 1` to your config file: https://zellij.dev/documentation/configuration

**Comment by xeros-and-ones** [comment] 2023-11-29 18:19
i'm also facing this issue and i tried adding `session_serialization 1` to the config file but that gives an error as it's a boolean. and the only way to workaround the issue is to run `zellij options --serialization-interval=1` but that takes away the capability of running zellij with attaching a specific session. is there a different workaround for this issue in the meantime.

**Comment by imsnif** [comment] 2023-11-29 18:41
This is fixed in `0.39.2`.

**Closed by imsnif** 2023-11-29 18:41 UTC
Labels: bug
