### ISSUE TITLE
header in Alacritty is disproportional

### ISSUE THREAD

**Issue by kontsaki** [zellij-org/zellij#301] opened 2021-04-21 07:10 UTC
Hello, directly running Zellij through the Alacritty terminal, as the startup shell program, _sometimes_ causes the header to have a wrong size

![zellij-bug](https://user-images.githubusercontent.com/60739442/115511425-1d3dc380-a281-11eb-98fc-688dedf3bb59.png)

**Comment by Keruspe** [comment] 2021-04-21 12:17
Missed this one when creating #303, this looks like the same issue?

100% reproducible with Germinal though

**Comment by imsnif** [comment] 2021-04-23 10:09
This is fixed in `0.5.1`. Thanks for the report!

**Closed by imsnif** 2021-04-23 10:09 UTC
Labels: bug
