### ISSUE TITLE
Color scheme within k9s is all wrong

### ISSUE THREAD

**Issue by qballer** [zellij-org/zellij#250] opened 2021-04-04 16:36 UTC
K9s is a Kubernetes command-line application. The first image is from within zellij and the second image is outside of zellij. 
As you can see the background color is getting weird. 
![Screen Shot 2021-04-04 at 19 33 32](https://user-images.githubusercontent.com/1002622/113515375-d2336900-957c-11eb-97fc-0eb9861cd6c2.png)
![Screen Shot 2021-04-04 at 19 33 48](https://user-images.githubusercontent.com/1002622/113515379-d3fd2c80-957c-11eb-931a-6f13111d95d6.png)

**Comment by a-kenji** [comment] 2021-04-04 16:45
Cheers!

I have similar issues in alacritty:
![20210404_18h42m39s_grim](https://user-images.githubusercontent.com/65275785/113515604-c5f7dd80-9575-11eb-9cf8-9ab67251eca7.png)

And in tmux from alacritty:
![20210404_18h41m55s_grim](https://user-images.githubusercontent.com/65275785/113515619-d7d98080-9575-11eb-9805-d5346d71e8cd.png)

**Comment by qballer** [comment] 2021-04-04 17:14
Weird worked fine for me in tmux

**Comment by a-kenji** [comment] 2021-04-04 17:17
It probably has more to do with my colorscheme in alacritty, if I were to guess.

**Comment by a-kenji** [comment] 2021-04-05 09:38
@qballer
It seems to be an interaction with the colorscheme, zellij and k9s.

I just tried it again with zellij and my default scheme:
![20210405_11h21m38s_grim](https://user-images.githubusercontent.com/65275785/113560459-54ff0700-9603-11eb-9fee-cc642ee686a2.png)
And with zellij and a different scheme:
![20210405_11h23m10s_grim](https://user-images.githubusercontent.com/65275785/113560484-60523280-9603-11eb-8a6a-c2288590e4ee.png)

**Comment by imsnif** [comment] 2021-04-05 14:38
@qballer, @a-kenji - I just merged some color fixes into main for a different issue. I tried to start k9s to check if it fixed it, but it's complaining that I don't have a kubernetes cluster (go fig :) ). Could you please check out the latest main to see if by any chance it fixed this?

**Comment by a-kenji** [comment] 2021-04-05 14:52
@imsnif ,
The latest main didn't fix it for me sadly.

**Comment by imsnif** [comment] 2021-04-05 14:56
> @imsnif ,
> The latest main didn't fix it for me sadly.

Thanks for checking! Could you then please run with --debug and send me the output so that I can debug this? (if you don't know --debug, it dumps everything from the pty into a file in /tmp/zellij-log - to make sure it works, you can copy that file aside (before quitting Zellij), and then cat it inside and outside a Zellij pane to see the difference).

**Comment by a-kenji** [comment] 2021-04-05 17:45
Sure! 
Here is the log file:
[zellij-3.log](https://github.com/zellij-org/zellij/files/6259639/zellij-3.log)

`k9s --version`:
Version:    0.24.5
Commit:     v0.24.5

**Comment by imsnif** [comment] 2021-04-06 13:17
Thanks for the log file. I found the issue (at least in the log file, I'm hoping it's the same issue all around) and fixed it.
@qballer + @a-kenji - could you please check out the latest main and verify the fix?

**Comment by a-kenji** [comment] 2021-04-06 16:14
@imsnif ,
Thanks! I can confirm that the latest main fixes the issue.

**Closed** 2021-04-07 10:18 UTC
Labels: bug
