### ISSUE TITLE
Error occurs when `cargo xtask run` in macOS

### ISSUE THREAD

**Issue by naosense** [zellij-org/zellij#2144] opened 2023-02-08 05:10 UTC
After updated the latest code 0255b56
```
> cargo xtask run

debug/zellij`

Error occurred in server:

  × Thread 'wasm' panicked.
  ├─▶ Originating Thread(s)
  │     1. ipc_server: NewClient
  │     2. screen_thread: NewTab
  │     3. plugin_thread: NewTab
  │
  ├─▶ At zellij-server/src/lib.rs:762:18
  ╰─▶ Program terminates: a fatal error occured

      Caused by:
          0: failed to load plugin for client 1
          1: failed to load plugin from instance Instance {
                 exports: {
                     (
                         "memory",
                         Memory(...),
                     ),
                     (
                         "__heap_base",
                         Global(...),
                     ),
                     (
                         "__data_end",
                         Global(...),
                     ),
                     (
                         "_start",
                         Function(...),
                     ),
                     (
                         "update",
                         Function(...),
                     ),
                     (
                         "render",
                         Function(...),
                     ),
                     (
                         "plugin_version",
                         Function(...),
                     ),
                     (
                         "main",
                         Function(...),
                     ),
                 },
             }
          2: RuntimeError: out of bounds memory access
          3: heap_get_oob
  help: If you are seeing this message, it means that something went wrong.

        -> To get additional information, check the log at: /var/folders/dr/y_q_0j3s4pj28s3rg91bjtgw0000gp/T/zellij-502/zellij-log/zellij.log
        -> To see a backtrace next time, reproduce the error with: RUST_BACKTRACE=1 zellij [...]
        -> To help us fix this, please open an issue: https://github.com/zellij-org/zellij/issues



Error: failed to run pipeline 'run' with args Run { args: [], data_dir: None, cranelift: false }

Caused by:
    command exited with non-zero code `/Users/xxx/.rustup/toolchains/stable-aarch64-apple-darwin/bin/cargo run --`: 1
```

**Comment by imsnif** [comment] 2023-02-08 08:13
Can you try clearing the plugin cache? By default I think it should be in ~/.local/cache/zellij/plugins
Also deleting the `target` folder might do the trick

**Comment by naosense** [comment] 2023-02-08 09:38
Deleting cache and target doesn't work for me, I'm using macOS if anyone who is also a Mac user can run it and see if it's my problem alone

**Comment by tlinford** [comment] 2023-02-08 16:51
Can confirm, same error running on macos.

**Comment by imsnif** [comment] 2023-02-08 17:07
@m-lima - any ideas?

**Comment by m-lima** [comment] 2023-02-08 17:50
I see from the logs that you are running `arm64`
> /Users/xxx/.rustup/toolchains/stable-aarch64-apple-darwin/bin/cargo run --

My work computer is a mac M1 as well, and I loaded it up there and got similar results.

@imsnif May I suggest that we reverse the defaults? As in, `singlepass` becomes an opt-in instead of default under debug.
When I was initially playing around with singlepass, I was using the M1, but did not come across this.
However, I can say it is pretty consistent on the mac M1 with the default run parameters in debug mode.

**Comment by imsnif** [comment] 2023-02-08 17:59
Makes sense (so that cranelift will be the default and singlepass (in development) will be opt-in, right?)

Do we know what's causing this? Is this a known issue with this engine? I guess it's probably fixed in the later versions?

**Comment by m-lima** [comment] 2023-02-08 18:07
I don't know exactly what is the issue. But it is consistent with the M1 running a default `cargo x run` in debug mode.
One hint is to look at the memory layout configuration for the singlepass compilation due to "memory out of bounds access".
But that is going to take longer than flipping the defaults, and I have no idea if that will help.
So, as the causer of this issue, I'd suggest flipping the defaults.

From wasmer v3 [release](https://wasmer.io/posts/announcing-wasmer-3.0):
> Singlepass Compiler Improvements
>
> The most popular compiler for blockchains got a lot of new improvements:
>
>    * Support for multi-value functions
>    * Improved robustness of the Singlepass compiler
>    * Added support for exception handling frames
>    * …and many more fixes and improvements (specially regarding performance!)

So maybe we get a fix for free once the upgrade is done.
However, I need to understand the error better before I can truly suggest that the version bump or the memory layout tweaks will help.
Fortunately, I have an arm64 that I can use.

**Comment by m-lima** [comment] 2023-02-08 18:22
https://github.com/wasmerio/wasmer/issues/3343

Also a out of bounds error on arm64. Suspiciously similar.
Fixed on Dec 8 2022

**Closed** 2023-02-13 16:52 UTC
